version: '3'
networks:
 laravel:

services:
 app:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: maratonador_app
  ports:
   - "8000:80"
  volumes:
   - .:/var/www/html
  depends_on:
   - mysql
  networks:
   - laravel

 mysql:
  image: mysql:5.7
  container_name: maratonador_banco
  tty: true
  ports:
   - "3306:3306"
  volumes:
   - ./.db:/var/lib/mysql
  environment:
   MYSQL_DATABASE: maratonador_banco
   MYSQL_PASSWORD: dundermifflin
   MYSQL_ROOT_PASSWORD: root
   MYSQL_USER: dwight
   SERVICE_TAGS: dev
   SERVICE_NAME: mysql
  networks:
   - laravel
